'use strict';

/**
 * Deneb ARC — PR Agent
 *
 * GitHub API integration for automated Pull Request creation.
 * Creates branches, commits files, and opens PRs from the user's
 * personal fork into the upstream deneb-ui organization repos.
 *
 * All commits are authored under the configured GITHUB_USERNAME
 * and GITHUB_EMAIL for full contribution credit.
 */

const { loadEnv } = require('./ai-agent.cjs');

/**
 * Get GitHub configuration from environment variables.
 */
function getGithubConfig() {
  return {
    pat: process.env.GITHUB_PAT || '',
    username: process.env.GITHUB_USERNAME || 'chamikathereal',
    email: process.env.GITHUB_EMAIL || 'dmforceeg@gmail.com',
    org: process.env.GITHUB_ORG || 'deneb-ui',
    coreRepo: process.env.GITHUB_CORE_REPO || 'core',
    uiRepo: process.env.GITHUB_UI_REPO || 'ui',
  };
}

/**
 * Check if GitHub integration is ready.
 * @returns {{ ready: boolean, reason?: string }}
 */
function checkGithubReady() {
  loadEnv();
  const config = getGithubConfig();
  if (!config.pat) {
    return { ready: false, reason: 'GITHUB_PAT not set. Generate a Personal Access Token at https://github.com/settings/tokens with "repo" scope.' };
  }
  if (!config.pat.startsWith('ghp_') && !config.pat.startsWith('github_pat_')) {
    return { ready: false, reason: 'GITHUB_PAT does not look valid (should start with ghp_ or github_pat_).' };
  }
  return { ready: true };
}

/**
 * Create a GitHub API client using @octokit/rest.
 * Returns null if the PAT is not configured.
 */
function createOctokitClient() {
  const config = getGithubConfig();
  if (!config.pat) return null;

  try {
    const { Octokit } = require('@octokit/rest');
    return new Octokit({ auth: config.pat });
  } catch {
    return null;
  }
}

/**
 * Get the SHA of the latest commit on a branch.
 */
async function getLatestCommitSha(octokit, owner, repo, branch = 'main') {
  const { data } = await octokit.repos.getBranch({
    owner,
    repo,
    branch,
  });
  return data.commit.sha;
}

/**
 * Create a new branch from the latest main.
 */
async function createBranch(octokit, owner, repo, branchName, baseSha) {
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });
}

/**
 * Create or update a file in a repository on a specific branch.
 */
async function createOrUpdateFile(octokit, owner, repo, branch, filePath, content, commitMessage) {
  const config = getGithubConfig();

  // Check if file already exists to get its SHA
  let existingSha;
  try {
    const { data } = await octokit.repos.getContent({
      owner,
      repo,
      path: filePath,
      ref: branch,
    });
    existingSha = data.sha;
  } catch {
    // File does not exist — will create
  }

  const params = {
    owner,
    repo,
    path: filePath,
    message: commitMessage,
    content: Buffer.from(content, 'utf8').toString('base64'),
    branch,
    committer: {
      name: config.username,
      email: config.email,
    },
    author: {
      name: config.username,
      email: config.email,
    },
  };
  if (existingSha) params.sha = existingSha;

  await octokit.repos.createOrUpdateFileContents(params);
}

/**
 * Open a Pull Request from the user's fork to the upstream repo.
 */
async function openPullRequest(octokit, { upstreamOwner, upstreamRepo, forkOwner, branch, title, body }) {
  const { data } = await octokit.pulls.create({
    owner: upstreamOwner,
    repo: upstreamRepo,
    title,
    body,
    head: `${forkOwner}:${branch}`,
    base: 'main',
  });
  return { number: data.number, url: data.html_url };
}

/**
 * Build a PR body with validation results and component details.
 */
function buildPrBody({ componentName, editableFields, attempts, totalInputTokens, totalOutputTokens, fingerprint }) {
  const fieldsTable = editableFields.map((f) => `| \`${f}\` |`).join('\n');

  return `## 🤖 AI-Generated Editable Component: \`Editable${componentName}\`

This component was automatically generated by **Deneb ARC AI Agent** and passed all validation checks.

### Editable Fields Discovered
| Field Path |
|---|
${fieldsTable}

### Validation Results
- ✅ AST Syntax: Passed
- ✅ Fivora Contract Markers: Passed
- ✅ TypeScript Interface: Passed
- ✅ Design Preservation: Intact

### Generation Stats
- **Model:** ${process.env.OPENAI_CONTENT_MODEL || 'gpt-4o-mini'}
- **Attempts:** ${attempts}/3
- **Tokens:** ${totalInputTokens.toLocaleString()} input / ${totalOutputTokens.toLocaleString()} output
- **Fingerprint:** \`${fingerprint || 'n/a'}\`

---
*Generated by Deneb ARC AI Agent — [deneb.fivora.site](https://deneb.fivora.site)*`;
}

/**
 * Full PR workflow: create branch → commit files → open PR.
 *
 * Opens PRs for both the core repo (component) and the ui repo (docs).
 *
 * @param {object} params
 * @param {string} params.componentName - e.g. "Carousel"
 * @param {string} params.componentCode - The validated EditableCarousel.tsx code
 * @param {string} params.docsCode - The generated docs page code (optional)
 * @param {string[]} params.editableFields - List of editable field paths
 * @param {number} params.attempts - Number of AI attempts taken
 * @param {number} params.totalInputTokens - Total tokens used
 * @param {number} params.totalOutputTokens - Total tokens used
 * @param {string} [params.fingerprint] - Structural fingerprint
 * @param {boolean} [params.dryRun=false] - If true, skip actual API calls
 * @returns {Promise<{ corePr?: { number: number, url: string }, uiPr?: { number: number, url: string }, errors: string[] }>}
 */
async function createComponentPR(params) {
  const {
    componentName,
    componentCode,
    docsCode,
    editableFields,
    attempts,
    totalInputTokens,
    totalOutputTokens,
    fingerprint,
    dryRun = false,
  } = params;

  const errors = [];
  let corePr = null;
  let uiPr = null;

  if (dryRun) {
    return {
      corePr: { number: 0, url: '(dry-run — PR not created)' },
      uiPr: docsCode ? { number: 0, url: '(dry-run — PR not created)' } : null,
      errors: [],
    };
  }

  const octokit = createOctokitClient();
  if (!octokit) {
    return { errors: ['GitHub client not available — check GITHUB_PAT and @octokit/rest installation.'] };
  }

  const config = getGithubConfig();
  const slugName = componentName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const timestamp = Date.now().toString(36);
  const prBody = buildPrBody({ componentName, editableFields, attempts, totalInputTokens, totalOutputTokens, fingerprint });

  // ── Core Repo PR ───────────────────────────────────────────────
  try {
    const coreBranch = `feat/ai-editable-${slugName}-${timestamp}`;
    const baseSha = await getLatestCommitSha(octokit, config.username, config.coreRepo);
    await createBranch(octokit, config.username, config.coreRepo, coreBranch, baseSha);

    // Commit the component file
    await createOrUpdateFile(
      octokit,
      config.username,
      config.coreRepo,
      coreBranch,
      `packages/deneb-ui/src/Editable${componentName}.tsx`,
      componentCode,
      `feat(ui): add Editable${componentName} component [AI-generated]`
    );

    // Open PR to upstream
    corePr = await openPullRequest(octokit, {
      upstreamOwner: config.org,
      upstreamRepo: config.coreRepo,
      forkOwner: config.username,
      branch: coreBranch,
      title: `feat(ui): add Editable${componentName} component [AI-generated]`,
      body: prBody,
    });
  } catch (err) {
    errors.push(`Core PR failed: ${err.message}`);
  }

  // ── UI Repo PR (docs page) ─────────────────────────────────────
  if (docsCode) {
    try {
      const uiBranch = `feat/ai-docs-${slugName}-${timestamp}`;
      const uiBaseSha = await getLatestCommitSha(octokit, config.username, config.uiRepo);
      await createBranch(octokit, config.username, config.uiRepo, uiBranch, uiBaseSha);

      // Commit the docs page
      await createOrUpdateFile(
        octokit,
        config.username,
        config.uiRepo,
        uiBranch,
        `src/app/docs/components/editable-${slugName}/page.tsx`,
        docsCode,
        `docs: add Editable${componentName} documentation [AI-generated]`
      );

      // Open PR to upstream
      uiPr = await openPullRequest(octokit, {
        upstreamOwner: config.org,
        upstreamRepo: config.uiRepo,
        forkOwner: config.username,
        branch: uiBranch,
        title: `docs: add Editable${componentName} documentation [AI-generated]`,
        body: prBody,
      });
    } catch (err) {
      errors.push(`UI docs PR failed: ${err.message}`);
    }
  }

  return { corePr, uiPr, errors };
}

module.exports = {
  getGithubConfig,
  checkGithubReady,
  createComponentPR,
  buildPrBody,
};
