import { ThemePalette } from './types';

export const THEME_PALETTES: ThemePalette[] = [
  // --- Light Themes ---
  {
    id: 'classic-luxe',
    name: 'Classic Luxe',
    badge: 'Light • Warm Luxe',
    mode: 'light',
    primary: '#1e293b',
    secondary: '#d97706',
    accent: '#f59e0b',
    background: '#fdfbf7',
    card: '#ffffff',
    text: '#1e293b',
    muted: '#64748b',
    buttonBg: '#1e293b',
    buttonText: '#ffffff',
  },
  {
    id: 'ocean-modern',
    name: 'Ocean Modern',
    badge: 'Light • Crisp Ocean',
    mode: 'light',
    primary: '#0284c7',
    secondary: '#0369a1',
    accent: '#38bdf8',
    background: '#f8fafc',
    card: '#ffffff',
    text: '#0f172a',
    muted: '#64748b',
    buttonBg: '#0284c7',
    buttonText: '#ffffff',
  },
  {
    id: 'forest-emerald',
    name: 'Forest Emerald',
    badge: 'Light • Organic Green',
    mode: 'light',
    primary: '#065f46',
    secondary: '#047857',
    accent: '#10b981',
    background: '#f0fdf4',
    card: '#ffffff',
    text: '#064e3b',
    muted: '#475569',
    buttonBg: '#065f46',
    buttonText: '#ffffff',
  },
  {
    id: 'warm-terracotta',
    name: 'Warm Terracotta',
    badge: 'Light • Artisanal',
    mode: 'light',
    primary: '#c2410c',
    secondary: '#ea580c',
    accent: '#f97316',
    background: '#fffaf5',
    card: '#ffffff',
    text: '#431407',
    muted: '#78350f',
    buttonBg: '#c2410c',
    buttonText: '#ffffff',
  },
  {
    id: 'velvet-berry',
    name: 'Velvet Berry',
    badge: 'Light • Vibrant Chic',
    mode: 'light',
    primary: '#9f1239',
    secondary: '#be123c',
    accent: '#f43f5e',
    background: '#fff5f7',
    card: '#ffffff',
    text: '#4c0519',
    muted: '#881337',
    buttonBg: '#9f1239',
    buttonText: '#ffffff',
  },
  // --- Dark Themes ---
  {
    id: 'sleek-obsidian',
    name: 'Sleek Obsidian',
    badge: 'Dark • Obsidian',
    mode: 'dark',
    primary: '#60a5fa',
    secondary: '#38bdf8',
    accent: '#93c5fd',
    background: '#090d16',
    card: '#131b2e',
    text: '#f8fafc',
    muted: '#94a3b8',
    buttonBg: '#60a5fa',
    buttonText: '#090d16',
  },
  {
    id: 'midnight-cyber',
    name: 'Midnight Cyber',
    badge: 'Dark • Neon Cyber',
    mode: 'dark',
    primary: '#818cf8',
    secondary: '#6366f1',
    accent: '#22d3ee',
    background: '#09090b',
    card: '#18181b',
    text: '#f4f4f5',
    muted: '#a1a1aa',
    buttonBg: '#818cf8',
    buttonText: '#09090b',
  },
  {
    id: 'royal-gold-dark',
    name: 'Royal Gold & Dark',
    badge: 'Dark • Imperial Gold',
    mode: 'dark',
    primary: '#f59e0b',
    secondary: '#d97706',
    accent: '#fbbf24',
    background: '#0c0a09',
    card: '#1c1917',
    text: '#f5f5f4',
    muted: '#a8a29e',
    buttonBg: '#f59e0b',
    buttonText: '#0c0a09',
  },
  {
    id: 'emerald-nocturne',
    name: 'Emerald Nocturne',
    badge: 'Dark • Deep Emerald',
    mode: 'dark',
    primary: '#34d399',
    secondary: '#10b981',
    accent: '#6ee7b7',
    background: '#022c22',
    card: '#064e3b',
    text: '#ecfdf5',
    muted: '#a7f3d0',
    buttonBg: '#34d399',
    buttonText: '#022c22',
  },
];
